# Generated by Django 4.2.6 on 2023-10-26 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('author', models.CharField(blank=True, max_length=125, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=125, null=True)),
                ('initial_review', models.TextField(blank=True, null=True)),
                ('image_s', models.CharField(blank=True, max_length=125, null=True)),
                ('image_m', models.CharField(blank=True, max_length=125, null=True)),
                ('image_l', models.CharField(blank=True, max_length=125, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
