# Generated by Django 4.2.6 on 2023-10-27 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreq',
            name='isbn',
            field=models.IntegerField(default=1000000000, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='bookreq',
            name='author',
            field=models.CharField(default='Anonimus', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookreq',
            name='initial_review',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bookreq',
            name='publisher',
            field=models.CharField(default='Penerbit Tidak Diketahui', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookreq',
            name='title',
            field=models.CharField(default='Judul Kosong', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookreq',
            name='year',
            field=models.IntegerField(default=1966, validators=[django.core.validators.MinValueValidator(1966), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
