# Generated by Django 4.2.6 on 2023-10-27 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0002_bookreq_isbn_alter_bookreq_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreq',
            name='isbn',
            field=models.CharField(default=1000000000, max_length=13, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='bookreq',
            name='year',
            field=models.CharField(default=1966, max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
